# Generated by Django 5.2.17 on 2026-09-22 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('required', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('display_order',),
            },
        ),
        migrations.CreateModel(
            name='ConsentPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_consent_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-effective_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_identifier', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('necessary', models.BooleanField(default=True)),
                ('functional', models.BooleanField(default=False)),
                ('analytics', models.BooleanField(default=False)),
                ('marketing', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='consent.consentpolicy')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-recorded_at',),
            },
        ),
        migrations.CreateModel(
            name='CookieDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('provider', models.CharField(default='SENZOFT', max_length=120)),
                ('purpose', models.TextField()),
                ('duration', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('storage_type', models.CharField(choices=[('COOKIE', 'Cookie'), ('LOCAL_STORAGE', 'Local storage'), ('SESSION_STORAGE', 'Session storage')], default='COOKIE', max_length=24)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=12)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='definitions', to='consent.cookiecategory')),
            ],
            options={
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('name', 'provider', 'storage_type'), name='unique_consent_storage_definition')],
            },
        ),
    ]
