# Generated by Django 5.2.17 on 2026-09-21 06:29

import core.ids
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=core.ids.notification_id, editable=False, max_length=20, unique=True)),
                ('notification_type', models.CharField(db_index=True, max_length=64)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('IN_APP', 'In-app')], max_length=16)),
                ('recipient', models.CharField(max_length=320)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='applications.application')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='careers.candidateprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='notificatio_status_9a4505_idx')],
            },
        ),
    ]
