import { useEffect, useState } from "react";
import { BriefcaseBusiness, ClipboardList, FileCheck2, ShieldCheck, UsersRound, Video } from "lucide-react";
import { Link } from "react-router-dom";
import { getDashboard, type DashboardData } from "../../services/api/admin";
import { AdminState, formatDate, StatusBadge } from "../AdminUI";

const cards = [
  ["jobs", "Jobs", BriefcaseBusiness, "/admin/jobs"], ["applications", "Applications", ClipboardList, "/admin/applications"],
  ["candidates", "Candidates", UsersRound, "/admin/candidates"], ["interviews", "Interviews", Video, "/admin/interviews"],
  ["pending_bgv", "Pending BGV", ShieldCheck, "/admin/bgv"], ["offers", "Offers", FileCheck2, "/admin/offers"],
] as const;

export default function AdminDashboardPage() {
  const [data, setData] = useState<DashboardData | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  async function load() { setLoading(true); setError(""); try { setData(await getDashboard()); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load dashboard."); } finally { setLoading(false); } }
  useEffect(() => { document.title = "Dashboard | SENZOFT Admin"; void load(); }, []);
  return <div className="admin-page"><header className="admin-page-header"><div><span className="admin-kicker">Recruitment overview</span><h1>Dashboard</h1><p>Live operational data from the SENZOFT recruitment platform.</p></div></header><AdminState loading={loading} error={error} empty={!data} onRetry={load}>{data && <><section className="admin-metric-grid" aria-label="Recruitment totals">{cards.map(([key, title, Icon, to]) => <Link to={to} className="admin-metric" key={key}><span><Icon /></span><div><strong>{data.counts[key]}</strong><p>{title}</p></div></Link>)}</section><div className="admin-dashboard-grid"><section className="admin-card admin-card-wide"><div className="admin-card-header"><h2>Recent applications</h2><Link to="/admin/applications">View all</Link></div>{data.recent_applications.length ? <div className="admin-list">{data.recent_applications.map((item) => <Link to={`/admin/applications/${item.id}`} key={item.id}><div><strong>{item.candidate_name}</strong><span>{item.job_title} · {formatDate(item.applied_at)}</span></div><StatusBadge value={item.current_status} /></Link>)}</div> : <p className="admin-empty-inline">No data available</p>}</section><section className="admin-card"><div className="admin-card-header"><h2>Status distribution</h2></div>{data.status_distribution.length ? <div className="admin-distribution">{data.status_distribution.map((item) => <div key={item.current_status}><span>{item.current_status.replaceAll("_", " ")}</span><strong>{item.count}</strong></div>)}</div> : <p className="admin-empty-inline">No data available</p>}</section><section className="admin-card"><div className="admin-card-header"><h2>Recent jobs</h2><Link to="/admin/jobs">View all</Link></div>{data.recent_jobs.length ? <div className="admin-list">{data.recent_jobs.map((job) => <Link to={`/admin/jobs/${job.id}`} key={job.id}><div><strong>{job.title}</strong><span>{job.department}</span></div><StatusBadge value={job.status} /></Link>)}</div> : <p className="admin-empty-inline">No data available</p>}</section><section className="admin-card"><div className="admin-card-header"><h2>Upcoming interviews</h2><Link to="/admin/interviews">View all</Link></div>{data.upcoming_interviews.length ? <div className="admin-list">{data.upcoming_interviews.map((interview) => <Link to={`/admin/interviews/${interview.id}`} key={interview.id}><div><strong>{interview.candidate_name}</strong><span>{interview.interview_type.replaceAll("_", " ")} · {formatDate(interview.scheduled_at)}</span></div></Link>)}</div> : <p className="admin-empty-inline">No data available</p>}</section></div></>}</AdminState></div>;
}
