import { useState } from "react";
import { Link } from "react-router-dom";
import { Search } from "lucide-react";
import { type AdminApplication } from "../../services/api/admin";
import { AdminState, formatDate, StatusBadge } from "../AdminUI";
import { useAdminList, useDebouncedValue } from "../useAdminList";

const statuses = ["APPLIED", "TALENT_REVIEW", "SHORTLISTED", "AI_INTERVIEW_INVITED", "AI_INTERVIEW_IN_PROGRESS", "AI_INTERVIEW_COMPLETED", "TECHNICAL_INTERVIEW", "HR_INTERVIEW", "DOCUMENTS_REQUESTED", "DOCUMENTS_SUBMITTED", "BACKGROUND_VERIFICATION", "BGV_COMPLETED", "OFFER_ISSUED", "OFFER_ACCEPTED", "JOINING_PROCESS", "JOINED", "REJECTED", "WITHDRAWN", "ON_HOLD", "CANCELLED", "OFFER_DECLINED", "NO_SHOW"];

export default function AdminApplicationsPage() {
  const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [page, setPage] = useState(1); const query = useDebouncedValue(search);
  const list = useAdminList<AdminApplication>("applications", { search: query, current_status: status, ordering: "-applied_at", page });
  return <div className="admin-page"><header className="admin-page-header"><div><span className="admin-kicker">Recruitment</span><h1>Applications</h1><p>Review candidates and move applications through validated workflow steps.</p></div></header><div className="admin-toolbar"><label className="admin-search"><Search /><span className="sr-only">Search applications</span><input value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="Search ID, candidate or job" /></label><label><span className="sr-only">Status</span><select value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }}><option value="">All statuses</option>{statuses.map((item) => <option key={item}>{item}</option>)}</select></label></div><AdminState loading={list.loading} error={list.error} empty={!list.data.results.length} onRetry={list.reload}><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Application</th><th>Candidate</th><th>Job</th><th>Applied</th><th>Status</th><th>Recruiter</th><th>Action</th></tr></thead><tbody>{list.data.results.map((item) => <tr key={item.id}><td data-label="Application"><strong>{item.id}</strong></td><td data-label="Candidate"><Link to={`/admin/candidates/${item.candidate_id}`}><strong>{item.candidate_name}</strong><span>{item.candidate_email}</span></Link></td><td data-label="Job">{item.job_title}<span>{item.job_id}</span></td><td data-label="Applied">{formatDate(item.applied_at)}</td><td data-label="Status"><StatusBadge value={item.current_status} /></td><td data-label="Recruiter">{item.recruiter_name || "Unassigned"}</td><td data-label="Action"><Link className="admin-table-link" to={`/admin/applications/${item.id}`}>Review</Link></td></tr>)}</tbody></table></div><div className="admin-pagination"><button disabled={page === 1} onClick={() => setPage((value) => value - 1)}>Previous</button><span>Page {page} · {list.data.count} records</span><button disabled={!list.data.next} onClick={() => setPage((value) => value + 1)}>Next</button></div></AdminState></div>;
}
