import { useState } from "react";
import { Search } from "lucide-react";
import { runAdminAction } from "../../services/api/admin";
import { AdminState, ConfirmDialog, formatDate, label, StatusBadge } from "../AdminUI";
import { useAdminList, useDebouncedValue } from "../useAdminList";

type User = { id: string; username: string; name: string; email: string; role: string; is_active: boolean; is_email_verified: boolean; date_joined: string; last_login: string | null };
type Audit = { id: string; timestamp: string; actor: string | null; action: string; entity: string; entity_id: string; metadata: Record<string, unknown> };
const roles = ["CANDIDATE", "RECRUITER", "HIRING_MANAGER", "INTERVIEWER", "HR", "ADMIN", "SUPER_ADMIN"];

export function AdminUsersPage() {
  const [search, setSearch] = useState(""); const [role, setRole] = useState(""); const [pending, setPending] = useState<{ user: User; type: "status" | "role"; value: string | boolean } | null>(null); const query = useDebouncedValue(search); const list = useAdminList<User>("users", { search: query, role, ordering: "username" });
  return <div className="admin-page"><header className="admin-page-header"><div><span className="admin-kicker">Administration</span><h1>Users</h1><p>Manage access status and recruitment roles through audited backend actions.</p></div></header><div className="admin-toolbar"><label className="admin-search"><Search /><input aria-label="Search users" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search username, name or email" /></label><select aria-label="Filter by role" value={role} onChange={(event) => setRole(event.target.value)}><option value="">All roles</option>{roles.map((item) => <option key={item}>{item}</option>)}</select></div><AdminState loading={list.loading} error={list.error} empty={!list.data.results.length} onRetry={list.reload}><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Joined</th><th>Last login</th><th>Actions</th></tr></thead><tbody>{list.data.results.map((user) => <tr key={user.id}><td data-label="User"><strong>{user.name || user.username}</strong><span>{user.email}</span></td><td data-label="Role"><select aria-label={`Role for ${user.username}`} value={user.role} onChange={(event) => setPending({ user, type: "role", value: event.target.value })}>{roles.map((item) => <option key={item}>{item}</option>)}</select></td><td data-label="Status"><StatusBadge value={user.is_active ? "ACTIVE" : "INACTIVE"} /></td><td data-label="Joined">{formatDate(user.date_joined)}</td><td data-label="Last login">{formatDate(user.last_login)}</td><td data-label="Actions"><button className={`admin-table-link ${user.is_active ? "danger" : ""}`} onClick={() => setPending({ user, type: "status", value: !user.is_active })}>{user.is_active ? "Deactivate" : "Activate"}</button></td></tr>)}</tbody></table></div></AdminState><ConfirmDialog open={Boolean(pending)} title={pending?.type === "role" ? "Change user role?" : `${pending?.value ? "Activate" : "Deactivate"} user?`} description={pending?.type === "role" ? `Change ${pending.user.username} to ${label(String(pending.value))}.` : "This immediately changes access to authenticated APIs."} confirmLabel="Confirm change" destructive={pending?.type === "status" && !pending.value} onClose={() => setPending(null)} onConfirm={async () => { if (!pending) return; await runAdminAction("users", pending.user.id, pending.type, pending.type === "role" ? { role: pending.value } : { is_active: pending.value }); await list.reload(); }} /></div>;
}

export function AdminAuditPage() {
  const [search, setSearch] = useState(""); const [action, setAction] = useState(""); const [entity, setEntity] = useState(""); const query = useDebouncedValue(search); const list = useAdminList<Audit>("audit", { search: query, action, entity, ordering: "-timestamp" });
  return <div className="admin-page"><header className="admin-page-header"><div><span className="admin-kicker">Security</span><h1>Audit logs</h1><p>Append-only records of important recruitment and administrative changes.</p></div></header><div className="admin-toolbar"><label className="admin-search"><Search /><input aria-label="Search audit logs" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search actor, action or entity ID" /></label><input aria-label="Filter by action" value={action} onChange={(event) => setAction(event.target.value.toUpperCase())} placeholder="Action" /><input aria-label="Filter by entity" value={entity} onChange={(event) => setEntity(event.target.value)} placeholder="Entity" /></div><AdminState loading={list.loading} error={list.error} empty={!list.data.results.length} onRetry={list.reload}><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Timestamp</th><th>Actor</th><th>Action</th><th>Entity</th><th>Entity ID</th></tr></thead><tbody>{list.data.results.map((item) => <tr key={item.id}><td data-label="Timestamp">{formatDate(item.timestamp)}</td><td data-label="Actor">{item.actor || "System"}</td><td data-label="Action"><strong>{label(item.action)}</strong></td><td data-label="Entity">{item.entity}</td><td data-label="Entity ID"><code>{item.entity_id}</code></td></tr>)}</tbody></table></div></AdminState></div>;
}
