# Generated by Django 5.2.17 on 2026-09-21 06:29

import core.ids
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=core.ids.candidate_id, editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('professional_summary', models.TextField(blank=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('experience', models.JSONField(blank=True, default=list)),
                ('education', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('resume_metadata', models.JSONField(blank=True, default=dict)),
                ('linkedin_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=core.ids.job_id, editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('department', models.CharField(db_index=True, max_length=120)),
                ('business_unit', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(db_index=True, max_length=160)),
                ('work_mode', models.CharField(choices=[('ONSITE', 'On-site'), ('HYBRID', 'Hybrid'), ('REMOTE', 'Remote')], db_index=True, max_length=16)),
                ('employment_type', models.CharField(db_index=True, max_length=64)),
                ('experience_level', models.CharField(blank=True, max_length=80)),
                ('minimum_experience', models.PositiveSmallIntegerField(default=0)),
                ('maximum_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('responsibilities', models.JSONField(default=list)),
                ('required_skills', models.JSONField(default=list)),
                ('preferred_skills', models.JSONField(blank=True, default=list)),
                ('qualifications', models.JSONField(blank=True, default=list)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('number_of_openings', models.PositiveSmallIntegerField(default=1)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending approval'), ('PUBLISHED', 'Published'), ('PAUSED', 'Paused'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=24)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'published_at'], name='careers_job_status_e8226c_idx'), models.Index(fields=['department', 'location'], name='careers_job_departm_edc61e_idx')],
            },
        ),
    ]
