# Generated by Django 5.2.17 on 2026-09-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='job',
            name='seo_title',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
