# Generated by Django 5.2.17 on 2026-09-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_job_seo_description_job_seo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='current_role',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='years_of_experience',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
