# Generated by Django 5.2.17 on 2026-09-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_candidateprofile_current_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='about_company',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='additional_locations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='hiring_eligibility',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='job',
            name='relocation_assistance',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='job',
            name='reporting_to',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='job',
            name='travel_requirement',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
