import { useEffect } from "react";
import { Navigate, Route, Routes } from "react-router-dom";
import { CandidateAuthProvider } from "./CandidateAuth";
import { CandidateProtected } from "./CandidateLayout";
import { CandidateForgotPasswordPage, CandidateLoginPage, CandidateRegisterPage } from "./pages/CandidateAuthPages";
import CandidateApplyPage from "./pages/CandidateApplyPage";
import { CandidateApplicationDetailPage, CandidateApplicationsPage, CandidateBgvPage, CandidateDashboardPage, CandidateDocumentsPage, CandidateEventsPage, CandidateInterviewDetailPage, CandidateJoiningPage, CandidateNotificationsPage, CandidateOfferDetailPage, CandidateOffersPage, CandidateProfilePage } from "./pages/CandidatePortalPages";
import "../styles/candidate.css";

function PrivateMetadata() { useEffect(() => { let meta = document.querySelector<HTMLMetaElement>('meta[name="robots"]'); if (!meta) { meta=document.createElement("meta"); meta.name="robots"; document.head.appendChild(meta); } meta.content="noindex, nofollow"; }, []); return null; }
export default function CandidateApp() { return <CandidateAuthProvider><PrivateMetadata /><Routes><Route path="login" element={<CandidateLoginPage />} /><Route path="register" element={<CandidateRegisterPage />} /><Route path="forgot-password" element={<CandidateForgotPasswordPage />} /><Route path="reset-password" element={<CandidateForgotPasswordPage />} /><Route element={<CandidateProtected />}><Route index element={<Navigate to="dashboard" replace />} /><Route path="dashboard" element={<CandidateDashboardPage />} /><Route path="profile" element={<CandidateProfilePage />} /><Route path="apply/:jobId" element={<CandidateApplyPage />} /><Route path="applications" element={<CandidateApplicationsPage />} /><Route path="applications/:id" element={<CandidateApplicationDetailPage />} /><Route path="events" element={<CandidateEventsPage />} /><Route path="interviews" element={<Navigate to="/candidate/events" replace />} /><Route path="interviews/:id" element={<CandidateInterviewDetailPage />} /><Route path="documents" element={<CandidateDocumentsPage />} /><Route path="background-verification" element={<CandidateBgvPage />} /><Route path="offers" element={<CandidateOffersPage />} /><Route path="offers/:id" element={<CandidateOfferDetailPage />} /><Route path="joining" element={<CandidateJoiningPage />} /><Route path="notifications" element={<CandidateNotificationsPage />} /></Route><Route path="*" element={<Navigate to="dashboard" replace />} /></Routes></CandidateAuthProvider>; }
