import { useEffect, useRef, useState } from "react";
import type { ConsentChoices, ConsentConfig } from "./types";

const descriptions: Record<keyof ConsentChoices, string> = { necessary: "Required for consent, security, authentication and core website operation.", functional: "Remembers optional interface and convenience preferences.", analytics: "Allows approved services to measure website usage and performance.", marketing: "Allows approved advertising or campaign-measurement services." };
export function CookiePreferences({ config, initial, onClose, onSave }: { config: ConsentConfig | null; initial: ConsentChoices; onClose: () => void; onSave: (value: ConsentChoices) => void }) {
  const [value, setValue] = useState<ConsentChoices>({ necessary: true, functional: initial.functional, analytics: initial.analytics, marketing: initial.marketing });
  const dialog = useRef<HTMLDivElement>(null);
  useEffect(() => { const previous = document.activeElement as HTMLElement | null; dialog.current?.focus(); const key = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; document.addEventListener("keydown", key); return () => { document.removeEventListener("keydown", key); previous?.focus(); }; }, [onClose]);
  return <div className="cookie-modal-backdrop" role="presentation"><div className="cookie-modal" role="dialog" aria-modal="true" aria-labelledby="cookie-settings-title" tabIndex={-1} ref={dialog}><header><div><span>Privacy controls</span><h2 id="cookie-settings-title">Cookie preferences</h2></div><button type="button" aria-label="Close cookie preferences" onClick={onClose}>×</button></header><p>Choose which optional categories SENZOFT may use. Necessary storage cannot be disabled.</p><div className="cookie-category-list">{(["necessary", "functional", "analytics", "marketing"] as const).map((key) => { const category = config?.categories.find((item) => item.key === key); return <section key={key}><div><strong>{category?.name ?? key[0].toUpperCase() + key.slice(1)}</strong><p>{category?.description ?? descriptions[key]}</p>{category?.definitions.map((item) => <small key={item.id}>{item.name} · {item.provider} · {item.duration}</small>)}</div><label className="cookie-switch"><input type="checkbox" checked={value[key]} disabled={key === "necessary"} aria-label={`${key} cookies`} onChange={(event) => setValue({ ...value, [key]: event.target.checked })}/><span>{key === "necessary" ? "Always active" : value[key] ? "On" : "Off"}</span></label></section>; })}</div><footer><button type="button" className="btn btn-outline" onClick={() => onSave({ ...value, functional: false, analytics: false, marketing: false })}>Reject optional</button><button type="button" className="btn btn-primary" onClick={() => onSave(value)}>Save preferences</button></footer></div></div>;
}

