# Generated by Django 5.2.17 on 2026-09-21 06:29

import core.ids
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=core.ids.application_id, editable=False, max_length=20, unique=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('current_status', models.CharField(choices=[('APPLIED', 'Applied'), ('TALENT_REVIEW', 'Talent review'), ('SHORTLISTED', 'Shortlisted'), ('AI_INTERVIEW_INVITED', 'AI interview invited'), ('AI_INTERVIEW_IN_PROGRESS', 'AI interview in progress'), ('AI_INTERVIEW_COMPLETED', 'AI interview completed'), ('TECHNICAL_INTERVIEW', 'Technical interview'), ('HR_INTERVIEW', 'HR interview'), ('DOCUMENTS_REQUESTED', 'Documents requested'), ('DOCUMENTS_SUBMITTED', 'Documents submitted'), ('BACKGROUND_VERIFICATION', 'Background verification'), ('BGV_COMPLETED', 'BGV completed'), ('OFFER_ISSUED', 'Offer issued'), ('OFFER_ACCEPTED', 'Offer accepted'), ('JOINING_PROCESS', 'Joining process'), ('JOINED', 'Joined'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('ON_HOLD', 'On hold'), ('CANCELLED', 'Cancelled'), ('OFFER_DECLINED', 'Offer declined'), ('NO_SHOW', 'No show')], db_index=True, default='APPLIED', max_length=32)),
                ('source', models.CharField(default='SENZOFT_WEBSITE', max_length=100)),
                ('resume_version', models.JSONField(default=dict)),
                ('profile_snapshot', models.JSONField(default=dict)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='careers.candidateprofile')),
                ('hiring_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='careers.job')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruited_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, max_length=32)),
                ('new_status', models.CharField(choices=[('APPLIED', 'Applied'), ('TALENT_REVIEW', 'Talent review'), ('SHORTLISTED', 'Shortlisted'), ('AI_INTERVIEW_INVITED', 'AI interview invited'), ('AI_INTERVIEW_IN_PROGRESS', 'AI interview in progress'), ('AI_INTERVIEW_COMPLETED', 'AI interview completed'), ('TECHNICAL_INTERVIEW', 'Technical interview'), ('HR_INTERVIEW', 'HR interview'), ('DOCUMENTS_REQUESTED', 'Documents requested'), ('DOCUMENTS_SUBMITTED', 'Documents submitted'), ('BACKGROUND_VERIFICATION', 'Background verification'), ('BGV_COMPLETED', 'BGV completed'), ('OFFER_ISSUED', 'Offer issued'), ('OFFER_ACCEPTED', 'Offer accepted'), ('JOINING_PROCESS', 'Joining process'), ('JOINED', 'Joined'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('ON_HOLD', 'On hold'), ('CANCELLED', 'Cancelled'), ('OFFER_DECLINED', 'Offer declined'), ('NO_SHOW', 'No show')], max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='applications.application')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='BackgroundVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=core.ids.bgv_id, editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('REQUESTED', 'Requested'), ('IN_PROGRESS', 'In progress'), ('VERIFICATION_REQUIRED', 'Verification required'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='NOT_STARTED', max_length=28)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='background_verification', to='applications.application')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='background_verifications', to='careers.candidateprofile')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bgv_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=core.ids.document_id, editable=False, max_length=20, unique=True)),
                ('document_type', models.CharField(choices=[('RESUME', 'Resume'), ('IDENTITY', 'Identity'), ('EDUCATION', 'Education'), ('EXPERIENCE', 'Experience'), ('ADDRESS_PROOF', 'Address proof'), ('OTHER', 'Other')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField()),
                ('mime_type', models.CharField(max_length=120)),
                ('storage_key', models.CharField(max_length=500, unique=True)),
                ('upload_status', models.CharField(choices=[('PENDING', 'Pending'), ('UPLOADED', 'Uploaded'), ('REVIEWED', 'Reviewed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='applications.application')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='careers.candidateprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=core.ids.interview_id, editable=False, max_length=20, unique=True)),
                ('interview_type', models.CharField(choices=[('AI_SCREENING', 'AI screening'), ('TECHNICAL', 'Technical'), ('HR', 'HR'), ('MANAGERIAL', 'Managerial'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No show')], default='SCHEDULED', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interviews', to='applications.application')),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterviewResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('transcript', models.TextField(blank=True)),
                ('evaluation', models.JSONField(blank=True, default=dict)),
                ('competency_signals', models.JSONField(blank=True, default=dict)),
                ('monitoring_events', models.JSONField(blank=True, default=list)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='applications.interview')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=core.ids.offer_id, editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending approval'), ('ISSUED', 'Issued'), ('VIEWED', 'Viewed'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=24)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='offer', to='applications.application')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='careers.candidateprofile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Joining',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default=core.ids.joining_id, editable=False, max_length=20, unique=True)),
                ('joining_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('JOINED', 'Joined'), ('NO_SHOW', 'No show'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('location', models.CharField(max_length=160)),
                ('department', models.CharField(max_length=120)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='joining', to='applications.application')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='joining_records', to='careers.candidateprofile')),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='joining', to='applications.offer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['current_status', 'applied_at'], name='application_current_8f33e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('candidate', 'job'), name='unique_candidate_job_application'),
        ),
    ]
