# Generated by Django 5.2.17 on 2026-09-21 10:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='configuration',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='interview',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='final_result',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='interviewresponse',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('READY', 'Ready'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No show'), ('EXPIRED', 'Expired'), ('FAILED', 'Failed')], default='SCHEDULED', max_length=20),
        ),
        migrations.CreateModel(
            name='InterviewEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technical_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('communication_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('relevance_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('overall_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('integrity_summary', models.JSONField(blank=True, default=dict)),
                ('structured_result', models.JSONField(blank=True, default=dict)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_summary', to='applications.interview')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('question', models.TextField(max_length=2000)),
                ('category', models.CharField(choices=[('TECHNICAL', 'Technical'), ('EXPERIENCE', 'Experience'), ('PROJECT', 'Project'), ('BEHAVIORAL', 'Behavioral')], max_length=20)),
                ('difficulty', models.CharField(default='MEDIUM', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='applications.interview')),
            ],
            options={
                'ordering': ('sequence',),
            },
        ),
        migrations.AddField(
            model_name='interviewresponse',
            name='question_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='response', to='applications.interviewquestion'),
        ),
        migrations.CreateModel(
            name='IntegrityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('severity', models.CharField(default='INFO', max_length=16)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrity_events', to='applications.interview')),
            ],
            options={
                'indexes': [models.Index(fields=['interview', 'occurred_at'], name='application_intervi_752a86_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='interviewquestion',
            constraint=models.UniqueConstraint(fields=('interview', 'sequence'), name='unique_interview_question_sequence'),
        ),
    ]
