# Generated by Django 5.2.17 on 2026-09-22 07:44

import applications.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_interview_configuration_interview_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment_type', models.CharField(choices=[('MEETING_LINK', 'Meeting link'), ('INTERVIEW_DOCUMENT', 'Interview document'), ('OFFER_LETTER', 'Offer letter'), ('OTHER', 'Other')], max_length=32)),
                ('title', models.CharField(max_length=160)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('file', models.FileField(blank=True, upload_to=applications.models.application_attachment_path)),
                ('note', models.TextField(blank=True)),
                ('visible_to_candidate', models.BooleanField(default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='applications.application')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
