import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { ArrowLeft, ArrowRight, Check, Search } from "lucide-react";
import { type FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { Link, Navigate, useLocation, useParams } from "react-router-dom";
import { CareerCta, CareerHeading, CareerIntro, JobCard, SampleNotice } from "../components/careers/CareersUI";
import { Seo } from "../components/ui/Seo";
import { benefits } from "../data/benefits";
import { categories, findCareerJob, jobs, type JobCategory } from "../data/jobs";

function MissingJob() { return <div className="container-shell py-36"><Seo title="Role not found | Senzoft" description="This sample role could not be found." /><h1 className="display text-5xl">Job not found</h1><p className="mt-5 text-brand-muted">This role may have moved or the link may be incorrect.</p><Link to="/careers/openings" className="btn btn-primary mt-8">Browse sample roles <ArrowRight size={17} /></Link></div>; }

export function LegacyCareerRedirect() {
  const { jobId } = useParams();
  const job = findCareerJob(jobId ?? "");
  return job ? <Navigate to={`/careers/openings/${job.id}`} replace /> : <MissingJob />;
}

export function CareerOpeningsPage() {
  const [category, setCategory] = useState<"all" | JobCategory>("all");
  const [search, setSearch] = useState("");
  const [department, setDepartment] = useState("all");
  const reduced = useReducedMotion();
  const departments = ["all", ...new Set(jobs.map((job) => job.department))];
  const filtered = useMemo(() => jobs.filter((job) => (category === "all" || job.category === category) && (department === "all" || job.department === department) && `${job.title} ${job.skills.join(" ")}`.toLowerCase().includes(search.trim().toLowerCase())), [category, department, search]);
  return <><Seo title="Explore Roles | Senzoft Careers" description="Browse illustrative career roles by category, department and skill." /><CareerIntro eyebrow="Career pathways" title="Explore roles" description="Find a direction that fits your interests and strengths. These sample roles show how career paths could be explored at Senzoft." /><section className="section"><div className="container-shell"><SampleNotice /><div className="mt-9 flex gap-2 overflow-x-auto border-b border-slate-200" role="tablist" aria-label="Role category">{categories.map((item) => <button key={item.value} type="button" role="tab" aria-selected={category === item.value} onClick={() => setCategory(item.value)} className="relative shrink-0 px-4 pb-4 pt-2 text-sm font-bold">{item.label}{category === item.value && <motion.span layoutId="career-active-tab" className="absolute inset-x-0 bottom-0 h-1 rounded-full bg-brand-orange" transition={{ duration: .25 }} />}</button>)}</div><div className="mt-7 grid gap-3 md:grid-cols-[1fr_240px]"><label className="relative"><span className="sr-only">Search title or skill</span><Search size={19} className="absolute left-4 top-1/2 -translate-y-1/2 text-brand-muted" /><input className="field w-full pl-12" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search title or skill" /></label><label><span className="sr-only">Department</span><select className="field w-full" value={department} onChange={(event) => setDepartment(event.target.value)}>{departments.map((item) => <option key={item} value={item}>{item === "all" ? "All departments" : item}</option>)}</select></label></div><p className="mt-6 text-sm text-brand-muted" aria-live="polite">{filtered.length} sample {filtered.length === 1 ? "role" : "roles"}</p><AnimatePresence mode="wait"><motion.div key={`${category}-${department}-${search}`} initial={reduced ? false : { opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={reduced ? undefined : { opacity: 0 }} transition={{ duration: .25 }} className="mt-5 grid gap-4 md:grid-cols-2">{filtered.map((job, index) => <JobCard key={job.id} job={job} index={index} />)}{filtered.length === 0 && <div className="rounded-2xl bg-brand-cream p-10 md:col-span-2"><h2 className="text-2xl font-bold">No openings right now — check back soon</h2><p className="mt-3 text-brand-muted">Try another category, department or search term.</p></div>}</motion.div></AnimatePresence></div></section><CareerCta /></>;
}

export function CareerJobDetailPage() {
  const { jobId } = useParams();
  const job = jobs.find((item) => item.id === jobId);
  const [showApply, setShowApply] = useState(false);
  const heroRef = useRef<HTMLDivElement>(null);
  useEffect(() => { const node = heroRef.current; if (!node) return; const observer = new IntersectionObserver(([entry]) => setShowApply(!entry.isIntersecting)); observer.observe(node); return () => observer.disconnect(); }, [jobId]);
  if (!job) return <MissingJob />;
  const similar = jobs.filter((item) => item.id !== job.id && item.category === job.category).slice(0, 3);
  return <><Seo title={`${job.title} | Senzoft Careers`} description={job.summary} /><div ref={heroRef}><CareerIntro eyebrow="Illustrative role" title={job.title} description={job.summary}><Link to="/careers/openings" className="btn btn-outline !border-white !text-white"><ArrowLeft size={16} /> All roles</Link></CareerIntro></div><section className="section"><div className="container-shell grid gap-12 lg:grid-cols-[1.4fr_.6fr]"><div><SampleNotice /><div className="mt-8 flex flex-wrap gap-3">{[job.department, job.location, job.type, job.experience, `Sample date: ${job.postedDate}`].map((item) => <span key={item} className="career-pill">{item}</span>)}</div><CareerHeading eyebrow="About the role" title="The work, at a glance." /><p className="max-w-3xl text-lg leading-9 text-brand-muted">{job.description}</p><h2 className="mt-12 text-2xl font-bold">Useful skills</h2><div className="mt-4 flex flex-wrap gap-2">{job.skills.map((skill) => <span key={skill} className="career-pill">{skill}</span>)}</div></div><aside className="lg:sticky lg:top-28 lg:self-start"><div className="career-info-card"><h2 className="text-2xl font-bold">Interested in this path?</h2><p className="mt-4 leading-7 text-brand-muted">Use the sample application flow to see what sharing your interest could look like.</p><Link to={`/careers/apply/${job.id}`} className="btn btn-primary mt-7">Apply now <ArrowRight size={17} /></Link></div></aside></div></section>{similar.length > 0 && <section className="section bg-brand-cream"><div className="container-shell"><CareerHeading eyebrow="Keep exploring" title="Similar roles" /><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{similar.map((item, index) => <JobCard key={item.id} job={item} index={index} />)}</div></div></section>}<AnimatePresence>{showApply && <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 20 }} transition={{ duration: .25 }} className="career-sticky-apply"><span className="hidden font-bold sm:inline">{job.title}</span><Link to={`/careers/apply/${job.id}`} className="btn btn-primary">Apply now <ArrowRight size={16} /></Link></motion.div>}</AnimatePresence></>;
}

export function CareerApplyPage() {
  const { jobId } = useParams();
  const job = jobs.find((item) => item.id === jobId);
  const [submitted, setSubmitted] = useState(false);
  const reduced = useReducedMotion();
  if (!job) return <MissingJob />;
  const jobTitle = job.title;
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const values = new FormData(event.currentTarget);
    const resume = values.get("resume");
    const body = [`Name: ${values.get("name")}`, `Email: ${values.get("email")}`, `Phone: ${values.get("phone")}`, `Cover note: ${values.get("note") || "—"}`, `Resume: ${resume instanceof File && resume.name ? resume.name + " (attach this file manually)" : "Not selected"}`].join("\n");
    window.location.href = `mailto:careers@senzoft.com?subject=${encodeURIComponent(`Application: ${jobTitle}`)}&body=${encodeURIComponent(body)}`;
    setSubmitted(true);
  }
  return <><Seo title={`Apply: ${job.title} | Senzoft Careers`} description={`Explore the sample application flow for ${job.title}.`} /><CareerIntro eyebrow="Application preview" title={`Apply for ${job.title}`} description="Share your details to prepare an email to the careers team. This sample form does not upload your resume or store your information." /><section className="section"><div className="container-shell max-w-3xl"><SampleNotice />{submitted ? <motion.div initial={reduced ? false : { opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .32 }} className="career-info-card mt-8 text-center"><motion.div initial={reduced ? false : { scale: .6 }} animate={{ scale: 1 }} transition={{ duration: .32 }} className="mx-auto grid size-16 place-items-center rounded-full bg-green-100 text-green-700"><Check size={34} /></motion.div><h2 className="display mt-7 text-4xl">Application email prepared</h2><p className="mt-4 leading-7 text-brand-muted">Complete the email in your mail app and attach your resume manually. Your application is sent only when you send that email.</p><Link to="/careers/openings" className="btn btn-primary mt-7">Back to roles</Link></motion.div> : <form onSubmit={submit} className="career-info-card mt-8 grid gap-5"><div className="grid gap-5 sm:grid-cols-2"><label className="font-bold">Full name<input required name="name" autoComplete="name" className="field mt-2 w-full" /></label><label className="font-bold">Email<input required name="email" type="email" autoComplete="email" className="field mt-2 w-full" /></label></div><label className="font-bold">Phone<input required name="phone" type="tel" autoComplete="tel" className="field mt-2 w-full" /></label><label className="font-bold">Resume<input name="resume" type="file" accept=".pdf,.doc,.docx" className="field mt-2 w-full" /><span className="mt-2 block text-xs font-normal text-brand-muted">The selected file cannot be attached automatically. Attach it in your email app.</span></label><label className="font-bold">Cover note<textarea name="note" rows={5} className="field mt-2 w-full" placeholder="Tell us about your interests and experience" /></label><button type="submit" className="btn btn-primary justify-self-start">Prepare application email <ArrowRight size={17} /></button></form>}</div></section></>;
}

export function CareerLifePage() {
  const { hash } = useLocation();
  useEffect(() => { if (hash) requestAnimationFrame(() => document.getElementById(hash.slice(1))?.scrollIntoView()); }, [hash]);
  return <><Seo title="Life at Senzoft | Careers" description="Explore how Senzoft teams collaborate, learn and grow." /><CareerIntro eyebrow="Life at Senzoft" title="Build together. Grow together." description="Meaningful work is shaped by curious people, open conversations and a shared commitment to useful outcomes." /><section id="culture" className="section scroll-mt-28"><div className="container-shell"><CareerHeading eyebrow="Our culture" title="Space for ideas and thoughtful work." copy="We value clear communication, practical problem solving and respect for different perspectives." /><div className="grid gap-4 md:grid-cols-3">{["Work across disciplines", "Share what you learn", "Own the outcome"].map((title, index) => <div key={title} className="career-info-card"><span className="text-sm font-bold text-brand-orange">0{index + 1}</span><h3 className="mt-6 text-2xl font-bold">{title}</h3><p className="mt-4 leading-7 text-brand-muted">{["Bring engineering, design and business viewpoints into the same conversation.", "Turn discoveries and feedback into better decisions for the next project.", "Keep the real user and business need in sight from start to finish."][index]}</p></div>)}</div></div></section><section id="growth" className="section scroll-mt-28 bg-brand-cream"><div className="container-shell"><CareerHeading eyebrow="Your growth" title="Learn by doing, with support." copy="A career develops through challenges, feedback and the chance to practice new skills." /><Link to="/careers/benefits" className="btn btn-primary">Explore benefits <ArrowRight size={17} /></Link></div></section><CareerCta /></>;
}

export function CareerBenefitsPage() { return <><Seo title="Benefits | Senzoft Careers" description="Explore the working experiences highlighted in Senzoft careers." /><CareerIntro eyebrow="Working here" title="The value of growing together." description="Explore the experiences and ways of working that can help people do their best work. Confirm specific employment benefits with the hiring team." /><section className="section"><div className="container-shell"><CareerHeading eyebrow="What to explore" title="Support for the work ahead." /><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{benefits.map((benefit, index) => <div key={benefit.title} className="career-info-card"><span className="text-sm font-bold text-brand-orange">0{index + 1}</span><h3 className="mt-7 text-2xl font-bold">{benefit.title}</h3><p className="mt-4 leading-7 text-brand-muted">{benefit.description}</p></div>)}</div></div></section><CareerCta /></>; }
