import { useMemo, useState } from 'react'
import { Search } from 'lucide-react'
import { PageHero } from '../components/ui/PageHero'
import { ContentGrid } from '../components/sections/ContentGrid'
import { CTA } from '../components/sections/CTA'
import { Seo } from '../components/ui/Seo'
import { contentRepository } from '../content/repository'

function Listing({kind,title,description,items,basePath}:{kind:string;title:string;description:string;items:Array<{slug:string;title:string;summary:string;icon?:string;eyebrow?:string;status?:string}>;basePath:string}){return <><Seo title={`${title} | SENZOFT`} description={description}/><PageHero eyebrow={kind} title={title} description={description}/><section className="section"><div className="container-shell"><ContentGrid items={items} basePath={basePath}/></div></section><CTA/></>}
export const ServicesPage=()=> <Listing kind="Capabilities" title="Expertise built around your ambition." description="From strategy through engineering and operations, we help organizations create confident, lasting change." items={contentRepository.getServices()} basePath="/services"/>
export const ProductsPage=()=> <Listing kind="Products" title="Software shaped around real work." description="Flexible SENZOFT product concepts designed to make complex operations clearer and more actionable." items={contentRepository.getProducts()} basePath="/products"/>
export const IndustriesPage=()=> <Listing kind="Industry context" title="Technology grounded in your world." description="Focused solutions that combine sector understanding with modern engineering, data and experience capabilities." items={contentRepository.getIndustries()} basePath="/industries"/>
export function InsightsPage(){const [query,setQuery]=useState('');const items=useMemo(()=>contentRepository.getInsights(query),[query]);return <><Seo title="Insights | SENZOFT" description="Perspectives on engineering, AI and enterprise transformation."/><PageHero eyebrow="Insights" title="Useful thinking for consequential change." description="Perspectives designed to make emerging technology and transformation decisions clearer."/><section className="section"><div className="container-shell"><label className="relative mb-10 block max-w-lg"><span className="sr-only">Search insights</span><Search className="absolute left-4 top-3.5 text-brand-muted" size={20}/><input className="field pl-12" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search insights"/></label>{items.length?<ContentGrid items={items} basePath="/insights"/>:<div className="rounded-2xl bg-brand-cream p-10"><h2 className="text-2xl font-bold">No matching insights</h2><p className="mt-2 text-brand-muted">Try a broader phrase or clear your search.</p></div>}</div></section></>}
export function CaseStudiesPage(){return <><Seo title="Case Studies | SENZOFT" description="SENZOFT client outcome stories."/><PageHero eyebrow="Client outcomes" title="Impact needs evidence." description="Approved client stories will appear here. We never publish unverified claims, logos or performance metrics."/><section className="section"><div className="container-shell rounded-3xl border border-dashed border-black/20 p-12 text-center"><h2 className="display text-4xl">Case studies in review</h2><p className="mx-auto mt-4 max-w-xl text-brand-muted">We are preparing client-approved stories. Talk to our team about experience relevant to your goals.</p></div></section><CTA/></>}
