import { useEffect, useMemo, useState } from "react";
import { Link, useLocation, useNavigate, useParams } from "react-router-dom";
import { ArrowLeft, ArrowRight, BriefcaseBusiness, MapPin, Search } from "lucide-react";
import { Seo } from "../components/ui/Seo";
import { getPublishedJob, getPublishedJobs, type ApiJob, type Paginated } from "../services/api/jobs";
import { tokenStore } from "../services/api/client";
import "../styles/candidate.css";

const show = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, c => c.toUpperCase());
const date = (value: string | null) => value ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium" }).format(new Date(value)) : "—";

export function PublicJobOpeningsPage() {
  const location = useLocation(); const navigate = useNavigate(); const initial = useMemo(() => new URLSearchParams(location.search), []);
  const [search,setSearch] = useState(initial.get("search") || ""); const [filters,setFilters] = useState({ department:initial.get("department")||"", location:initial.get("location")||"", work_mode:initial.get("workMode")||"", employment_type:initial.get("employmentType")||"", experience_level:initial.get("experience")||"", ordering:initial.get("ordering")||"-published_at" }); const [page,setPage]=useState(Number(initial.get("page"))||1); const [data,setData]=useState<Paginated<ApiJob>|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [debounced,setDebounced]=useState(search);
  useEffect(() => { const timer=window.setTimeout(()=>setDebounced(search),350); return()=>window.clearTimeout(timer); },[search]);
  useEffect(() => { const params=new URLSearchParams(); if(debounced)params.set("search",debounced); Object.entries(filters).forEach(([key,value])=>{if(value)params.set(key==="work_mode"?"workMode":key==="employment_type"?"employmentType":key==="experience_level"?"experience":key,value)}); if(page>1)params.set("page",String(page)); navigate({search:params.toString()},{replace:true}); const api=new URLSearchParams(); if(debounced)api.set("search",debounced); Object.entries(filters).forEach(([key,value])=>{if(value)api.set(key,value)}); api.set("page",String(page)); setLoading(true); setError(""); getPublishedJobs(api.toString()).then(setData).catch(reason=>setError(reason instanceof Error?reason.message:"Unable to load jobs.")).finally(()=>setLoading(false)); },[debounced,filters,page]);
  const setFilter=(key:keyof typeof filters,value:string)=>{setFilters(current=>({...current,[key]:value}));setPage(1)};
  return <><Seo title="Open Positions | SENZOFT Careers" description="Explore current published career opportunities at SENZOFT." /><header className="career-api-hero"><div className="container-shell"><p>Careers at SENZOFT</p><h1>Open positions</h1><span>Explore current opportunities and find work aligned with your experience.</span></div></header><main className="section"><div className="container-shell"><div className="career-job-filters"><label className="career-search"><Search/><span className="sr-only">Search jobs</span><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Search title, skills, or description" /></label>{(["department","location","work_mode","employment_type","experience_level"] as const).map(key=><label key={key}><span>{show(key)}</span><input value={filters[key]} onChange={e=>setFilter(key,e.target.value)} placeholder={`Any ${show(key).toLowerCase()}`} /></label>)}<label><span>Sort</span><select value={filters.ordering} onChange={e=>setFilter("ordering",e.target.value)}><option value="-published_at">Newest</option><option value="published_at">Oldest</option><option value="title">Title A–Z</option><option value="application_deadline">Deadline</option></select></label></div>{loading?<div className="career-api-state">Loading published jobs…</div>:error?<div className="career-api-state error"><p>{error}</p><button onClick={()=>setPage(value=>value)}>Retry</button></div>:!data?.results.length?<div className="career-api-state"><h2>No matching positions</h2><p>Adjust the filters or check again later.</p></div>:<><p className="career-result-count">{data.count} published {data.count===1?"position":"positions"}</p><div className="career-job-grid">{data.results.map(job=><JobCard key={job.id} job={job}/>)}</div><div className="career-pagination"><button disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page}</span><button disabled={!data.next} onClick={()=>setPage(page+1)}>Next</button></div></>}</div></main></>;
}
function JobCard({job}:{job:ApiJob}) { return <article className="career-api-job"><div><span>{job.id}</span><h2><Link to={`/careers/openings/${job.id}`}>{job.title}</Link></h2><p>{job.description}</p></div><dl><div><dt><BriefcaseBusiness/>Department</dt><dd>{job.department}</dd></div><div><dt><MapPin/>Location</dt><dd>{job.location}</dd></div><div><dt>Work mode</dt><dd>{show(job.work_mode)}</dd></div><div><dt>Experience</dt><dd>{job.minimum_experience}–{job.maximum_experience ?? `${job.minimum_experience}+`} years</dd></div><div><dt>Posted</dt><dd>{date(job.published_at)}</dd></div><div><dt>Deadline</dt><dd>{date(job.application_deadline)}</dd></div></dl><Link className="btn btn-primary" to={`/careers/openings/${job.id}`}>View role <ArrowRight/></Link></article>; }

export function PublicJobDetailPage() { const {jobId=""}=useParams(); const [job,setJob]=useState<ApiJob|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); useEffect(()=>{setLoading(true);getPublishedJob(jobId).then(setJob).catch(reason=>setError(reason instanceof Error?reason.message:"Job not found.")).finally(()=>setLoading(false))},[jobId]); const apply=()=>{const target=`/candidate/apply/${jobId}`;if(!tokenStore.access()){sessionStorage.setItem("candidate-return-to",target)}}; if(loading)return <div className="career-api-state">Loading role…</div>; if(error||!job)return <div className="career-api-state error"><h1>Position unavailable</h1><p>{error}</p><Link to="/careers/openings">View open positions</Link></div>; const applyTo=tokenStore.access()?`/candidate/apply/${job.id}`:"/candidate/login"; return <><Seo title={job.title} description={job.description.slice(0,155)} /><header className="career-api-detail-hero"><div className="container-shell"><Link to="/careers/openings"><ArrowLeft/>All positions</Link><p>{job.id} · {job.department}</p><h1>{job.title}</h1><div>{[job.location,show(job.work_mode),show(job.employment_type),`${job.minimum_experience}–${job.maximum_experience??job.minimum_experience+"+"} years`].map(item=><span key={item}>{item}</span>)}</div><Link className="btn btn-primary" onClick={apply} to={applyTo}>Apply now <ArrowRight/></Link></div></header><main className="section"><div className="container-shell career-detail-layout"><article><JobSection title="Overview" text={job.description}/><JobList title="Responsibilities" items={job.responsibilities}/><JobList title="Required skills" items={job.required_skills}/><JobList title="Preferred skills" items={job.preferred_skills}/><JobList title="Qualifications" items={job.qualifications}/><JobList title="Benefits" items={job.benefits}/></article><aside className="career-application-info"><h2>Application information</h2><dl><div><dt>Job ID</dt><dd>{job.id}</dd></div><div><dt>Published</dt><dd>{date(job.published_at)}</dd></div><div><dt>Deadline</dt><dd>{date(job.application_deadline)}</dd></div><div><dt>Openings</dt><dd>{job.number_of_openings}</dd></div></dl><Link className="btn btn-primary" onClick={apply} to={applyTo}>Apply for this role</Link></aside></div></main></>; }
function JobSection({title,text}:{title:string;text:string}){return <section className="career-job-section"><h2>{title}</h2><p>{text}</p></section>}; function JobList({title,items}:{title:string;items:string[]}){if(!items.length)return null;return <section className="career-job-section"><h2>{title}</h2><ul>{items.map(item=><li key={item}>{item}</li>)}</ul></section>}
