import type { Insight } from "../types";

const seo = (title: string, description: string) => ({
  title: `${title} | SENZOFT`,
  description,
});

export const insights: Insight[] = [
  {
    id: "insight-1",
    slug: "from-ai-pilot-to-practical-value",
    title: "From AI pilot to practical value",
    summary: "The useful unit of AI investment is a better workflow, with a clear owner and a way to judge whether it helped.",
    status: "published",
    type: "Perspective",
    readTime: "8 min read",
    publishedAt: "2026-08-20",
    seo: seo("From AI pilot to practical value", "A practical guide to turning AI experiments into useful, owned workflows."),
  },
  {
    id: "insight-2",
    slug: "modernization-without-disruption",
    title: "Modernization without disruption",
    summary: "A modernization roadmap should explain how the business keeps operating at every intermediate step.",
    status: "published",
    type: "Article",
    readTime: "9 min read",
    publishedAt: "2026-08-12",
    seo: seo("Modernization without disruption", "How to modernize applications while protecting business continuity."),
  },
  {
    id: "insight-3",
    slug: "designing-trusted-digital-services",
    title: "Designing trusted digital services",
    summary: "Trust grows when a service is understandable, recoverable and consistent at the moments that matter.",
    status: "published",
    type: "Perspective",
    readTime: "7 min read",
    publishedAt: "2026-07-28",
    seo: seo("Designing trusted digital services", "Design principles for digital services people can understand and rely on."),
  },
  {
    id: "insight-4",
    slug: "cloud-cost-to-cloud-value",
    title: "From cloud cost to cloud value",
    summary: "Cloud spending becomes more useful when teams can connect it to a workload, an owner and a business outcome.",
    status: "published",
    type: "Report",
    readTime: "10 min read",
    publishedAt: "2026-07-16",
    seo: seo("From cloud cost to cloud value", "Connect cloud spending to workload ownership and business value."),
  },
  {
    id: "insight-5",
    slug: "quality-engineering-in-ai-era",
    title: "Quality engineering in the AI era",
    summary: "AI changes how software is produced and how some features behave; neither change removes the need for independent evidence.",
    status: "published",
    type: "Article",
    readTime: "8 min read",
    publishedAt: "2026-07-03",
    seo: seo("Quality engineering in the AI era", "How teams can evaluate software and AI-enabled features with confidence."),
  },
  {
    id: "insight-6",
    slug: "secure-modernization-roadmap",
    title: "The secure modernization roadmap",
    summary: "Modernization creates an opportunity to simplify trust boundaries, provided security decisions are made before migration.",
    status: "published",
    type: "Perspective",
    readTime: "9 min read",
    publishedAt: "2026-06-19",
    seo: seo("The secure modernization roadmap", "Security decisions that belong in every application modernization plan."),
  },
  ...[
    ["build-vs-buy", "When should an enterprise build instead of buy?", "Perspective", "Evaluate differentiation, control, integration and total ownership before committing."],
    ["api-modernization-roadmap", "What a good API modernization roadmap looks like", "Guide", "A staged approach to discovering and modernizing enterprise interfaces."],
    ["data-foundations-for-ai", "Designing data foundations for AI", "Article", "Why ownership, quality and access matter more than model selection alone."],
    ["measuring-modernization", "Making legacy modernization measurable", "Article", "Define signals for risk, delivery speed, reliability and readiness."],
    ["software-as-capability", "When software becomes an operating capability", "Perspective", "Move from project delivery toward enduring product ownership."],
    ["user-behavior-digital-products", "Building digital products around real user behavior", "Guide", "Use evidence from users and operations to shape product decisions."],
    ["observability-architecture", "Why observability belongs in architecture decisions", "Article", "Treat logs, metrics and traces as part of system design."],
    ["staged-cloud-modernization", "How to approach cloud modernization in stages", "Guide", "Sequence cloud change around dependencies and operational readiness."],
    ["testing-ai-applications", "Testing AI-enabled applications", "Article", "Test probabilistic behavior, integrations, safety and conventional software together."],
    ["reliable-workflow-automation", "Designing reliable workflow automation", "Article", "Make automated processes observable, recoverable and understandable."],
    ["genai-questions-leaders", "What enterprise teams should ask before adopting generative AI", "Guide", "Examine use-case fit, data, security, governance and operating cost."],
    ["data-governance-engineering", "Data governance as an engineering practice", "Perspective", "Move governance from policy documents into ownership and delivery controls."],
    ["accessible-digital-experiences", "Building accessible digital experiences", "Guide", "Practical accessibility considerations across design, engineering and testing."],
    ["dashboards-to-decisions", "From dashboards to decision systems", "Perspective", "Move from reporting activity toward repeatable decision support."],
    ["api-first-modernization", "API-first modernization for connected enterprises", "Article", "Use stable interfaces to reduce coupling across the application landscape."],
    ["quality-delivery-economics", "How quality engineering changes delivery economics", "Perspective", "Use earlier quality signals to reduce rework and release uncertainty."],
    ["practical-cloud-security", "Practical cloud security for modern applications", "Guide", "Place controls across identity, infrastructure, applications and delivery."],
    ["resilient-customer-journeys", "Designing resilient customer journeys", "Article", "Design journeys that recover gracefully when dependencies fail."],
    ["platform-engineering-guide", "A practical guide to platform engineering", "Guide", "Know when internal platforms accelerate teams and when they add complexity."],
    ["technology-roadmap", "How to plan a technology roadmap without overcommitting", "Perspective", "Balance ambition, dependencies, capability and investment."],
    ["product-thinking-enterprise", "The role of product thinking in enterprise software", "Article", "Use continuous ownership to improve long-lived enterprise systems."],
    ["internal-knowledge-assistants", "Building internal knowledge assistants responsibly", "Guide", "Design retrieval, permissions, evaluation and human review together."],
    ["maintainable-enterprise-apps", "What makes an enterprise application maintainable?", "Article", "Explore boundaries, ownership, observability, testing and documentation."],
    ["modernization-beyond-migration", "Measuring modernization beyond migration", "Perspective", "Judge modernization by the capability and outcomes it enables."],
  ].map(([slug, title, type, summary], index) => ({
    id: `insight-${index + 7}`,
    slug,
    title,
    summary,
    status: "published" as const,
    type: type as Insight["type"],
    readTime: type === "Guide" ? "12 min read" : "8 min read",
    publishedAt: `2026-${String(Math.max(1, 6 - Math.floor(index / 4))).padStart(2, "0")}-${String(24 - (index % 4) * 5).padStart(2, "0")}`,
    seo: seo(title, summary),
  })),
];
