import { FormEvent, useState } from "react";
import { Link, Navigate, useLocation, useNavigate } from "react-router-dom";
import { ArrowRight } from "lucide-react";
import { registerCandidate } from "../../services/api/auth";
import { useCandidateAuth } from "../CandidateAuth";

export function CandidateLoginPage() {
  const { user, login } = useCandidateAuth(); const navigate = useNavigate(); const location = useLocation();
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  if (user) return <Navigate to="/candidate/dashboard" replace />;
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(""); try { await login(email, password); const destination = (location.state as { returnTo?: string } | null)?.returnTo || sessionStorage.getItem("candidate-return-to") || "/candidate/dashboard"; sessionStorage.removeItem("candidate-return-to"); navigate(destination, { replace: true }); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to sign in."); } finally { setSaving(false); } };
  return <AuthShell title="Welcome back" copy="Sign in to manage your SENZOFT applications."><form onSubmit={submit} className="candidate-auth-form">{error && <p className="candidate-form-error" role="alert">{error}</p>}<label>Email<input type="email" autoComplete="email" required value={email} onChange={(e) => setEmail(e.target.value)} /></label><label>Password<input type="password" autoComplete="current-password" required value={password} onChange={(e) => setPassword(e.target.value)} /></label><button className="candidate-btn primary" disabled={saving}>{saving ? "Signing in…" : <>Sign in <ArrowRight /></>}</button><div className="candidate-auth-links"><Link to="/candidate/forgot-password">Forgot password?</Link><span>New candidate? <Link to="/candidate/register" state={location.state}>Create an account</Link></span></div></form></AuthShell>;
}

export function CandidateRegisterPage() {
  const navigate = useNavigate(); const location = useLocation(); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const password = String(data.get("password")); if (password !== data.get("confirm")) { setError("Passwords do not match."); return; } setSaving(true); setError(""); try { const email = String(data.get("email")).trim().toLowerCase(); await registerCandidate({ username: email, email, password, first_name: String(data.get("first_name")).trim(), last_name: String(data.get("last_name")).trim(), phone: String(data.get("phone")).trim() }); navigate("/candidate/login", { replace: true, state: location.state }); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to register."); } finally { setSaving(false); } };
  return <AuthShell title="Create your candidate account" copy="Use one secure account to apply and track your progress."><form onSubmit={submit} className="candidate-auth-form two-column">{error && <p className="candidate-form-error wide" role="alert">{error}</p>}<label>First name<input name="first_name" autoComplete="given-name" required /></label><label>Last name<input name="last_name" autoComplete="family-name" required /></label><label className="wide">Email<input name="email" type="email" autoComplete="email" required /></label><label className="wide">Phone<input name="phone" type="tel" autoComplete="tel" required /></label><label>Password<input name="password" type="password" minLength={10} autoComplete="new-password" required /></label><label>Confirm password<input name="confirm" type="password" minLength={10} autoComplete="new-password" required /></label><button className="candidate-btn primary wide" disabled={saving}>{saving ? "Creating account…" : "Create account"}</button><p className="wide">Already registered? <Link to="/candidate/login" state={location.state}>Sign in</Link></p></form></AuthShell>;
}

export function CandidateForgotPasswordPage() { return <AuthShell title="Reset your password" copy="Automated password-reset delivery is not enabled yet."><div className="candidate-auth-form"><p>Contact the SENZOFT recruitment team using the email address associated with your account. No reset email has been sent from this screen.</p><Link className="candidate-btn secondary" to="/candidate/login">Back to sign in</Link></div></AuthShell>; }

function AuthShell({ title, copy, children }: { title: string; copy: string; children: React.ReactNode }) { return <main className="candidate-auth-page"><section className="candidate-auth-brand"><Link to="/">SENZOFT</Link><div><p>Candidate portal</p><h1>Your next opportunity, clearly tracked.</h1><span>Explore roles, submit applications, and follow every confirmed hiring update.</span></div></section><section className="candidate-auth-panel"><div className="candidate-auth-card"><p className="candidate-kicker">Careers at SENZOFT</p><h2>{title}</h2><p>{copy}</p>{children}</div></section></main>; }
