import { FormEvent, useState } from "react";
import { Link, Navigate, useLocation, useNavigate } from "react-router-dom";
import { ArrowLeft, ArrowRight, MailCheck } from "lucide-react";
import { getCountries, getCountryCallingCode, getExampleNumber, parsePhoneNumberFromString, type CountryCode } from "libphonenumber-js";
import mobileExamples from "libphonenumber-js/examples.mobile.json";
import { PasswordField } from "../../components/ui/PasswordField";
import { registerCandidate, resendLoginCode, type AuthChallenge } from "../../services/api/auth";
import { useCandidateAuth } from "../CandidateAuth";

const countryNames = new Intl.DisplayNames(["en"], { type: "region" });
const countries = getCountries().map(code => ({ code, name: countryNames.of(code) || code, callingCode: getCountryCallingCode(code) })).sort((a,b)=>a.name.localeCompare(b.name));
const phoneLimit = (country: CountryCode) => getExampleNumber(country, mobileExamples)?.nationalNumber.length ?? 15;

export function CandidateLoginPage() {
  const { user, login, verify } = useCandidateAuth(); const navigate = useNavigate(); const location = useLocation();
  const [email, setEmail] = useState(""); const [challenge,setChallenge]=useState<AuthChallenge|null>(null); const [code,setCode]=useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  if (user) return <Navigate to="/candidate/dashboard" replace />;
  const destination = () => (location.state as { returnTo?: string } | null)?.returnTo || sessionStorage.getItem("candidate-return-to") || "/candidate/dashboard";
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(""); try { setChallenge(await login(email)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to send verification code."); } finally { setSaving(false); } };
  const confirm = async (event:FormEvent)=>{event.preventDefault();if(!challenge)return;setSaving(true);setError("");try{await verify(challenge.challenge_id,code);sessionStorage.removeItem("candidate-return-to");navigate(destination(),{replace:true})}catch(reason){setError(reason instanceof Error?reason.message:"Unable to verify code.")}finally{setSaving(false)}};
  const resend=async()=>{if(!challenge)return;setSaving(true);setError("");try{setChallenge(await resendLoginCode(challenge.challenge_id));setCode("")}catch(reason){setError(reason instanceof Error?reason.message:"Unable to resend code.")}finally{setSaving(false)}};
  if(challenge)return <AuthShell title="Check your email" copy={`Enter the six-digit code sent to ${challenge.email}.`}><VerificationForm code={code} setCode={setCode} error={error} saving={saving} onSubmit={confirm} onResend={resend} onBack={()=>{setChallenge(null);setCode("");setError("")}} /></AuthShell>;
  return <AuthShell title="Welcome back" copy="Enter your registered email and we will send a secure one-time code."><form onSubmit={submit} className="candidate-auth-form">{error && <p className="candidate-form-error" role="alert">{error}</p>}<label>Email<input type="email" autoComplete="email" required value={email} onChange={(e) => setEmail(e.target.value)} /></label><button className="candidate-btn primary" disabled={saving || !email.trim()}>{saving ? "Sending code…" : <>Email verification code <ArrowRight /></>}</button><div className="candidate-auth-links"><span>New candidate? <Link to="/candidate/register" state={location.state}>Create an account</Link></span></div></form></AuthShell>;
}

export function CandidateRegisterPage() {
  const {verify}=useCandidateAuth(); const navigate = useNavigate(); const location = useLocation(); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const [country,setCountry]=useState<CountryCode>("IN"); const [phone,setPhone]=useState(""); const [challenge,setChallenge]=useState<AuthChallenge|null>(null); const [code,setCode]=useState("");
  const limit=phoneLimit(country);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const password = String(data.get("password")); if (password !== data.get("confirm")) { setError("Passwords do not match."); return; } const parsedPhone=parsePhoneNumberFromString(phone,country); const phoneType=parsedPhone?.getType(); if(!parsedPhone?.isValid()||!(["MOBILE","FIXED_LINE_OR_MOBILE"] as Array<string|undefined>).includes(phoneType)){setError(`Enter a valid ${limit}-digit mobile number for ${countryNames.of(country)}.`);return;} setSaving(true); setError(""); try { const email = String(data.get("email")).trim().toLowerCase(); setChallenge(await registerCandidate({ username: email, email, password, first_name: String(data.get("first_name")).trim(), last_name: String(data.get("last_name")).trim(), phone, phone_country:country })); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to register."); } finally { setSaving(false); } };
  const confirm=async(event:FormEvent)=>{event.preventDefault();if(!challenge)return;setSaving(true);setError("");try{await verify(challenge.challenge_id,code);navigate("/candidate/dashboard",{replace:true,state:location.state})}catch(reason){setError(reason instanceof Error?reason.message:"Unable to verify code.")}finally{setSaving(false)}};
  const resend=async()=>{if(!challenge)return;setSaving(true);setError("");try{setChallenge(await resendLoginCode(challenge.challenge_id));setCode("")}catch(reason){setError(reason instanceof Error?reason.message:"Unable to resend code.")}finally{setSaving(false)}};
  if(challenge)return <AuthShell title="Verify your email" copy={`We sent a six-digit code to ${challenge.email}.`}><VerificationForm code={code} setCode={setCode} error={error} saving={saving} onSubmit={confirm} onResend={resend} /></AuthShell>;
  return <AuthShell title="Create your candidate account" copy="Use one secure account to apply and track your progress."><form onSubmit={submit} className="candidate-auth-form two-column">{error && <p className="candidate-form-error wide" role="alert">{error}</p>}<label>First name<input name="first_name" autoComplete="given-name" required /></label><label>Last name<input name="last_name" autoComplete="family-name" required /></label><label className="wide">Email<input name="email" type="email" autoComplete="email" required /></label><label className="wide">Mobile number<div className="phone-field"><select aria-label="Country code" value={country} onChange={event=>{setCountry(event.target.value as CountryCode);setPhone("")}}>{countries.map(item=><option key={item.code} value={item.code}>{item.code} +{item.callingCode} — {item.name}</option>)}</select><input name="phone" type="tel" inputMode="numeric" pattern="[0-9]*" autoComplete="tel-national" required maxLength={limit} value={phone} onChange={event=>setPhone(event.target.value.replace(/\D/g,"").slice(0,limit))} placeholder={`${limit}-digit mobile number`} /></div><small>Digits only · {limit} digits for {countryNames.of(country)}</small></label><label>Password<PasswordField name="password" minLength={10} autoComplete="new-password" required /></label><label>Confirm password<PasswordField name="confirm" minLength={10} autoComplete="new-password" required /></label><button className="candidate-btn primary wide" disabled={saving}>{saving ? "Creating account…" : "Create account"}</button><p className="wide">Already registered? <Link to="/candidate/login" state={location.state}>Sign in</Link></p></form></AuthShell>;
}

function VerificationForm({code,setCode,error,saving,onSubmit,onResend,onBack}:{code:string;setCode:(value:string)=>void;error:string;saving:boolean;onSubmit:(event:FormEvent)=>void;onResend:()=>void;onBack?:()=>void}){return <form onSubmit={onSubmit} className="candidate-auth-form candidate-verification-form"><MailCheck className="verification-icon" aria-hidden="true"/>{error&&<p className="candidate-form-error" role="alert">{error}</p>}<label>Verification code<input className="verification-code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required value={code} onChange={event=>setCode(event.target.value.replace(/\D/g,"").slice(0,6))} placeholder="000000" /></label><button className="candidate-btn primary" disabled={saving||code.length!==6}>{saving?"Verifying…":"Verify and continue"}</button><button className="candidate-btn secondary" type="button" disabled={saving} onClick={onResend}>Send a new code</button>{onBack&&<button className="candidate-auth-back" type="button" onClick={onBack}><ArrowLeft/>Use another account</button>}</form>}

export function CandidateForgotPasswordPage() { return <AuthShell title="Reset your password" copy="Automated password-reset delivery is not enabled yet."><div className="candidate-auth-form"><p>Contact the SENZOFT recruitment team using the email address associated with your account. No reset email has been sent from this screen.</p><Link className="candidate-btn secondary" to="/candidate/login">Back to sign in</Link></div></AuthShell>; }

function AuthShell({ title, copy, children }: { title: string; copy: string; children: React.ReactNode }) { return <main className="candidate-auth-page"><section className="candidate-auth-brand"><Link to="/">SENZOFT</Link><div><p>Candidate portal</p><h1>Your next opportunity, clearly tracked.</h1><span>Explore roles, submit applications, and follow every confirmed hiring update.</span></div></section><section className="candidate-auth-panel"><div className="candidate-auth-card"><p className="candidate-kicker">Careers at SENZOFT</p><h2>{title}</h2><p>{copy}</p>{children}</div></section></main>; }
