import { useEffect, useRef, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { Camera, CheckCircle2, Mic, MicOff, RefreshCw, ShieldAlert } from "lucide-react";
import { completeInterview, getInterviewSession, recordIntegrityEvent, startInterview, submitInterviewResponse, type InterviewQuestion, type InterviewSession } from "../../services/api/candidate";
import { CandidateStatus } from "../CandidateUI";

type SpeechRecognitionLike = { continuous:boolean; interimResults:boolean; lang:string; start:()=>void; stop:()=>void; onresult:((event:{results:ArrayLike<{0:{transcript:string}}>})=>void)|null; onend:(()=>void)|null; onerror:(()=>void)|null };
export default function CandidateInterviewRoomPage() {
  const { id="" }=useParams(); const videoRef=useRef<HTMLVideoElement>(null); const streamRef=useRef<MediaStream|null>(null); const recognitionRef=useRef<SpeechRecognitionLike|null>(null);
  const [session,setSession]=useState<InterviewSession|null>(null); const [permission,setPermission]=useState<"idle"|"checking"|"ready"|"denied"|"unavailable">("idle"); const [transcript,setTranscript]=useState(""); const [listening,setListening]=useState(false); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
  const load=async()=>{try{setSession(await getInterviewSession(id))}catch(reason){setError(reason instanceof Error?reason.message:"Unable to load interview.")}}; useEffect(()=>{void load();return()=>streamRef.current?.getTracks().forEach(track=>track.stop())},[id]);
  const signal=(event_type:string,severity="INFO",metadata:Record<string,unknown>={})=>{if(session?.status==="IN_PROGRESS")void recordIntegrityEvent(id,event_type,severity,metadata).catch(()=>undefined)};
  useEffect(()=>{const visibility=()=>{if(document.hidden)signal("TAB_HIDDEN","WARNING")};const blur=()=>signal("WINDOW_BLUR","WARNING");const offline=()=>signal("CONNECTION_INTERRUPTION","WARNING");const fullscreen=()=>{if(!document.fullscreenElement)signal("FULLSCREEN_EXIT","INFO")};document.addEventListener("visibilitychange",visibility);window.addEventListener("blur",blur);window.addEventListener("offline",offline);document.addEventListener("fullscreenchange",fullscreen);return()=>{document.removeEventListener("visibilitychange",visibility);window.removeEventListener("blur",blur);window.removeEventListener("offline",offline);document.removeEventListener("fullscreenchange",fullscreen)}},[session?.status,id]);
  useEffect(()=>{if(session?.status!=="IN_PROGRESS")return;const tracks=streamRef.current?.getVideoTracks()||[];const stopped=()=>signal("CAMERA_STOPPED","CRITICAL");tracks.forEach(track=>track.addEventListener("ended",stopped));const Detector=(window as unknown as {FaceDetector?:new(options:{maxDetectedFaces:number})=>{detect:(source:HTMLVideoElement)=>Promise<unknown[]>}}).FaceDetector;let timer=0;if(Detector&&videoRef.current){const detector=new Detector({maxDetectedFaces:3});timer=window.setInterval(()=>{if(!videoRef.current)return;detector.detect(videoRef.current).then(faces=>{if(faces.length===0)signal("FACE_MISSING","WARNING");else if(faces.length>1)signal("MULTIPLE_FACES","WARNING");else signal("FACE_PRESENT","INFO")}).catch(()=>undefined)},10000)}return()=>{tracks.forEach(track=>track.removeEventListener("ended",stopped));if(timer)window.clearInterval(timer)}},[session?.status,id]);
  const checkDevices=async()=>{setPermission("checking");setError("");try{const stream=await navigator.mediaDevices.getUserMedia({video:true,audio:true});streamRef.current=stream;if(videoRef.current)videoRef.current.srcObject=stream;setPermission("ready")}catch(reason){const denied=reason instanceof DOMException&&reason.name==="NotAllowedError";setPermission(denied?"denied":"unavailable");setError(denied?"Camera and microphone permission was denied. Enable access in browser settings and retry.":"A camera or microphone is unavailable on this device.")}};
  const begin=async()=>{if(permission!=="ready")return;setSaving(true);setError("");try{await document.documentElement.requestFullscreen?.().catch(()=>undefined);setSession(await startInterview(id))}catch(reason){setError(reason instanceof Error?reason.message:"Unable to start interview.")}finally{setSaving(false)}};
  const current:InterviewQuestion|undefined=session?.questions.find(question=>!question.answered);
  const toggleListening=()=>{if(listening){recognitionRef.current?.stop();setListening(false);return}const source=window as unknown as {SpeechRecognition?:new()=>SpeechRecognitionLike;webkitSpeechRecognition?:new()=>SpeechRecognitionLike};const SpeechCtor=source.SpeechRecognition||source.webkitSpeechRecognition;if(!SpeechCtor){setError("Live browser speech recognition is unavailable. Type your answer instead.");return}const recognition=new SpeechCtor();recognition.continuous=true;recognition.interimResults=false;recognition.lang="en-IN";recognition.onresult=event=>{let text="";for(let i=0;i<event.results.length;i++)text+=event.results[i][0].transcript+" ";setTranscript(value=>(value+" "+text).trim())};recognition.onend=()=>setListening(false);recognition.onerror=()=>{setListening(false);setError("Speech recognition stopped. You can continue by typing.")};recognitionRef.current=recognition;recognition.start();setListening(true)};
  const submit=async()=>{if(!current||!transcript.trim()||saving)return;setSaving(true);setError("");try{await submitInterviewResponse(id,current.id,transcript.trim());setTranscript("");await load()}catch(reason){setError(reason instanceof Error?reason.message:"Unable to submit answer.")}finally{setSaving(false)}};
  const complete=async()=>{setSaving(true);setError("");try{setSession(await completeInterview(id));streamRef.current?.getTracks().forEach(track=>track.stop());if(document.fullscreenElement)await document.exitFullscreen()}catch(reason){setError(reason instanceof Error?reason.message:"Unable to complete interview.")}finally{setSaving(false)}};
  if(!session&&!error)return <div className="candidate-state">Loading interview…</div>; if(!session)return <div className="candidate-state error"><p>{error}</p><button onClick={()=>void load()}>Retry</button></div>;
  if(session.status==="COMPLETED")return <section className="interview-complete"><CheckCircle2/><h1>Interview completed</h1><p>Your structured responses are available to the recruitment team for human review. AI output is not an automatic hiring decision.</p><Link className="candidate-btn primary" to="/candidate/interviews">Back to interviews</Link></section>;
  const answered=session.responses.length,total=session.questions.length||Number(session.configuration.maximum_questions||0);return <section className="interview-room"><header className="interview-header"><div><p className="candidate-kicker">AI initial screening</p><h1>{session.job_title}</h1><p>{session.id}</p></div><div><CandidateStatus value={session.status}/><strong>{answered} / {total} answered</strong></div></header><div className="interview-progress"><span style={{width:`${total?Math.min(100,answered/total*100):0}%`}}/></div>{error&&<div className="candidate-form-error" role="alert">{error}</div>}<div className="interview-grid"><aside className="interview-camera"><video ref={videoRef} autoPlay muted playsInline/><div className="camera-status"><Camera/><span>Camera: {permission}</span>{listening?<Mic/>:<MicOff/>}</div>{permission!=="ready"&&<div className="camera-overlay"><ShieldAlert/><p>Camera and microphone are used only during this session. No audio or video recording is stored.</p><button className="candidate-btn secondary" onClick={()=>void checkDevices()} disabled={permission==="checking"}><RefreshCw/> {permission==="checking"?"Checking…":"Check camera and microphone"}</button></div>}</aside><main className="interview-question">{session.status!=="IN_PROGRESS"?<><p className="candidate-kicker">Before you begin</p><h2>System check and interview guidance</h2><ul><li>Use a quiet, well-lit location.</li><li>Keep this tab visible during the interview.</li><li>Answer in your own words; transcripts are retained, media is not.</li><li>Integrity events are signals for review, not proof of misconduct.</li></ul><button className="candidate-btn primary" disabled={permission!=="ready"||saving} onClick={()=>void begin()}>{saving?"Starting…":"Start interview"}</button></>:current?<><p className="candidate-kicker">Question {current.sequence} · {current.category} · {current.difficulty}</p><h2>{current.question}</h2><label>Your answer transcript<textarea rows={9} maxLength={12000} value={transcript} onChange={event=>setTranscript(event.target.value)} placeholder="Speak using the microphone button or type your answer."/></label><div className="interview-actions"><button className={`candidate-btn ${listening?"danger":"secondary"}`} onClick={toggleListening}>{listening?<><MicOff/>Stop listening</>:<><Mic/>Start listening</>}</button><button className="candidate-btn primary" disabled={!transcript.trim()||saving} onClick={()=>void submit()}>{saving?"Evaluating…":"Submit answer"}</button></div></>:<><h2>All available questions answered</h2><p>Complete the interview to submit the structured result for human review.</p><button className="candidate-btn primary" disabled={saving} onClick={()=>void complete()}>{saving?"Completing…":"Complete interview"}</button></>}</main></div></section>;
}
