import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { CheckCircle2 } from "lucide-react";
import { getProfile, listApplications, submitApplication, type CandidateApplication, type CandidateProfile } from "../../services/api/candidate";
import { getPublishedJob, type ApiJob } from "../../services/api/jobs";
import { CandidateState, CandidateStatus, formatDate } from "../CandidateUI";

export default function CandidateApplyPage() {
  const { jobId = "" } = useParams(); const navigate = useNavigate();
  const [job,setJob] = useState<ApiJob|null>(null); const [profile,setProfile] = useState<CandidateProfile|null>(null); const [existing,setExisting] = useState<CandidateApplication|null>(null); const [submitted,setSubmitted] = useState<CandidateApplication|null>(null); const [loading,setLoading] = useState(true); const [saving,setSaving] = useState(false); const [error,setError] = useState("");
  const load = async () => { setLoading(true); setError(""); try { const [jobData, profileData, apps] = await Promise.all([getPublishedJob(jobId), getProfile(), listApplications()]); setJob(jobData); setProfile(profileData); setExisting(apps.results.find(app => app.job === jobId) || null); } catch(reason) { setError(reason instanceof Error ? reason.message : "Unable to prepare application."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [jobId]);
  const missing = profile ? [["phone",profile.phone],["location",profile.location],["professional summary",profile.professional_summary],["skills",profile.skills.length],["experience",profile.experience.length],["education",profile.education.length]].filter(([,value]) => !value).map(([name]) => name) : [];
  const submit = async () => { if (!profile || saving) return; setSaving(true); setError(""); try { setSubmitted(await submitApplication(jobId, profile.resume_metadata)); } catch(reason) { setError(reason instanceof Error ? reason.message : "Unable to submit application."); } finally { setSaving(false); } };
  if (submitted) return <section><header className="candidate-page-header"><p className="candidate-kicker">Application submitted successfully</p><h1>{submitted.job_title}</h1><p>Your application is now recorded in the recruitment system.</p></header><article className="candidate-card submitted"><CheckCircle2 /><dl><div><dt>Job ID</dt><dd>{submitted.job}</dd></div><div><dt>Application ID</dt><dd>{submitted.id}</dd></div><div><dt>Submitted</dt><dd>{formatDate(submitted.applied_at)}</dd></div><div><dt>Status</dt><dd><CandidateStatus value={submitted.current_status} /></dd></div></dl><div><Link className="candidate-btn primary" to={`/candidate/applications/${submitted.id}`}>View application</Link><Link className="candidate-btn secondary" to="/candidate/applications">My applications</Link></div></article></section>;
  return <section><header className="candidate-page-header"><p className="candidate-kicker">Review and submit</p><h1>{job?.title || "Application"}</h1><p>Confirm the job and profile information that will be snapshotted with this application.</p></header><CandidateState loading={loading} error={error} empty={!job || !profile} onRetry={load}>{job && profile && (existing ? <article className="candidate-card submitted"><h2>Already applied</h2><p>Application ID: <strong>{existing.id}</strong></p><CandidateStatus value={existing.current_status} /><Link className="candidate-btn primary" to={`/candidate/applications/${existing.id}`}>View application</Link></article> : <div className="candidate-apply-review"><article className="candidate-card"><h2>Job</h2><p><strong>{job.title}</strong></p><p>{job.id} · {job.department} · {job.location}</p></article><article className="candidate-card"><h2>Candidate profile</h2><p><strong>{profile.name}</strong> · {profile.email}</p><p>{profile.phone || "Phone missing"} · {profile.location || "Location missing"}</p><p>{profile.professional_summary || "Professional summary missing"}</p></article><article className="candidate-card"><h2>Resume and history</h2><p>Resume: {Object.keys(profile.resume_metadata).length ? String(profile.resume_metadata.file_name || "Metadata on file") : "No stored resume"}</p><p>Skills: {profile.skills.join(", ") || "Not provided"}</p><p>Experience entries: {profile.experience.length} · Education entries: {profile.education.length}</p></article>{missing.length > 0 && <div className="candidate-warning" role="alert"><strong>Complete your profile before applying.</strong><p>Missing: {missing.join(", ")}.</p><Link to="/candidate/profile" className="candidate-btn secondary">Edit profile</Link></div>}<div className="candidate-form-actions"><button className="candidate-btn secondary" onClick={() => navigate(-1)}>Back</button><Link className="candidate-btn secondary" to="/candidate/profile">Edit profile</Link><button className="candidate-btn primary" disabled={saving || missing.length > 0} onClick={() => void submit()}>{saving ? "Submitting…" : "Submit application"}</button></div></div>)}</CandidateState></section>;
}
